		keyTable.put("0", "`");
		keyTable.put(")","~");
		keyTable.put("y","1");
		keyTable.put("`","!");
		keyTable.put("@","2");
		keyTable.put("Y","@");
		keyTable.put("#","3");
		keyTable.put("z","#");
		keyTable.put("m","4");
		keyTable.put("M","$");
		System.out.println("10 : "+keyTable.size());
		keyTable.put("5","5");
		keyTable.put("^","%");
		keyTable.put("t","6");
		keyTable.put("T","^");
		keyTable.put("k","7");
		keyTable.put("K","&");
		keyTable.put("]","8");
		keyTable.put("{","*");
		keyTable.put("g","9");
		keyTable.put("G","(");
		System.out.println("20 : "+keyTable.size());
		keyTable.put("f","0");
		keyTable.put("F",")");
		keyTable.put("_","-");
		keyTable.put("-","_");
		keyTable.put("=","=");
		keyTable.put("+","+");
		keyTable.put("6","q");
		keyTable.put(".","Q");
		keyTable.put("c","w");
		keyTable.put("D","W");
		System.out.println("30 : "+keyTable.size());
		keyTable.put("e","e");